apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldaf-ws
  labels:
    app: ldaf-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
      loc: connection
  template:
    metadata:
      labels:
        app: ws
        loc: connection
    spec:
      containers:
      - name: ldaf-ws
        image: dolencd/ldafv2ws
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 8547