services:
  - docker
  - redis
  - rabbitmq
language: node_js
node_js:
  - 12

env:
  global:
    - REDIS_HOST=localhost
    - REDIS_PORT=6379

install:
  - npm i -g typescript lerna
  - lerna link
  - lerna bootstrap
  - lerna run compile

script: 
  - lerna run test
  - lerna run verdaccio_publish
  - lerna run build


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - lerna run push
  - docker logout