version: '3.8'
services:
    rabbit:
        image: rabbitmq:3
        ports:
            - target: 15672
              published: 8080
              protocol: tcp
              mode: host
        networks:
            - main

    redis:
        image: "redis:alpine"
        networks:  
            - main

    udp:
        build: "./packages/UdpConnection"
        ports:
            - target: 41234
              published: 41234
              protocol: udp
              mode: host
        networks:
            - main
        depends_on:
            - redis
            - rabbit
        environment:
            UDP_FORWARDING_SERVICE: nidd
            REDIS_HOST: redis
            REDIS_PORT: 6379
            RABBITMQ_ADDRESS: amqp://rabbit

    service:
        build: "./packages/Service"
        depends_on:
            - redis
            - rabbit
        environment:
            SRC_GIT: https://tsnidd:mC62^Kyt@git.ltfe.org/dejandolenc/nidd-service
            REDIS_HOST: redis
            REDIS_PORT: 6379
            RABBITMQ_ADDRESS: amqp://rabbit
        networks:
            - main

    


networks:
    main: