apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      loc: core
  template:
    metadata:
      labels:
        app: rabbitmq
        loc: core
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  selector:
    app: rabbitmq
    loc: core
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672