apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldafv2-s
  labels:
    app: ldafv2-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldafv2-s
  template:
    metadata:
      labels:
        app: ldafv2-s
    spec:
      containers:
      - name: ldafv2-s
        image: dolencd/ldafv2service
        env: 
          - name: RABBITMQ_ADDRESS
            value: "amqp://rabbitmq-svc"
          - name: REDIS_HOST
            value: "redis-svc"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"