apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldaf-ws
  labels:
    app: ldaf-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
      loc: connection
  template:
    metadata:
      labels:
        app: ws
        loc: connection
    spec:
      containers:
      - name: ldaf-ws
        image: dolencd/ldafv2ws
        env: 
          - name: RABBITMQ_ADDRESS
            value: "amqp://rabbitmq-svc"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 8547
---
apiVersion: v1
kind: Service
metadata:
  name: ldaf-ws-lb
spec:
  selector:
    app: ws
    loc: connection
  ports:
    - port: 8547
      targetPort: 8547
  type: LoadBalancer