apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldaf-udp
  labels:
    app: ldaf-udp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp
      loc: connection
  template:
    metadata:
      labels:
        app: udp
        loc: connection
    spec:
      containers:
      - name: ldaf-udp
        image: dolencd/ldafv2udp
        env: 
          - name: RABBITMQ_ADDRESS
            value: "amqp://rabbitmq-svc"
          - name: REDIS_HOST
            value: "redis_svc"
          - name: UDP_FORWARDING_SERVICE
            value: 
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 41234
---
apiVersion: v1
kind: Service
metadata:
  name: ldaf-udp-lb
spec:
  selector:
    app: udp
    loc: connection
  ports:
    - port: 41234
      protocol: UDP
      targetPort: 41234
  type: LoadBalancer